
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: LoadBalancer  # Expose the service outside of the cluster
  ports:
  - port: 80
    targetPort: 5000
