
FROM registry.suse.com/bci/bci-base:15.5
RUN zypper install -y sqlite3
WORKDIR /data
RUN mkdir images dbase
COPY setup_db.sql /data/dbase/
COPY load_images.sh /data/dbase/
RUN sqlite3 /data/dbase/images.db < /data/dbase/setup_db.sql
CMD tail -f /dev/null
