
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite-db
spec:
  selector:
    matchLabels:
      app: sqlite-db
  template:
    metadata:
      labels:
        app: sqlite-db
    spec:
      containers:
      - name: sqlite-db
        image: sqlite-db-image
        volumeMounts:
        - name: data-storage
          mountPath: /data
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-pvc
