apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite-db
  template:
    metadata:
      labels:
        app: sqlite-db
    spec:
      containers:
      - name: sqlite-db
        image: pi-gallery-sqlite:latest
        volumeMounts:
        - name: data-storage
          mountPath: /data
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # This line is optional if you want to specify a storage class
  # storageClassName: "your-storage-class-name"
